export const initialQuoteItemsArray = [
    {
      quoteName: 'number of pages',
      startingValue: 20,
      steps: 20,
      selectionOne: '1 - 10',
      selectionTwo: '10 - 50',
      selectionThree: '50 - 150',
      selectionFour: '150 - 250',
      selectionFive: '250+',
      costPerPage: 100
    },
    {
      quoteName: 'style of design',
      startingValue: 25,
      steps: 25,
      selectionOne: 'Simple',
      selectionTwo: 'Moderate',
      selectionThree: 'High End',
      selectionFour: 'World Class',
      costOne: 1000,
      costTwo: 3000,
      costThree: 5000,
      costFour: 10000
    },
    {
      quoteName: 'seo integration',
      startingValue: 0,
      steps: 100,
      selectionOne: 'No',
      selectionTwo: 'Yes',
      costOne: 0,
      costTwo: 2000,
      costPerPage: 100
    },
    {
      quoteName: 'responsive design',
      startingValue: 0,
      steps: 100,
      selectionOne: 'No',
      selectionTwo: 'Yes',
      costOne: 0,
      costTwo: 1500
    },
    {
      quoteName: 'e-commerce functionality',
      startingValue: 25,
      steps: 25,
      selectionOne: 'None',
      selectionTwo: 'Basic',
      selectionThree: 'Advanced',
      selectionFour: 'Enterprise',
      costOne: 0,
      costTwo: 3000,
      costThree: 6000,
      costFour: 10000
    },
    {
      quoteName: 'database integration',
      startingValue: 25,
      steps: 25,
      selectionOne: 'None',
      selectionTwo: 'Basic',
      selectionThree: 'Advanced',
      selectionFour: 'Enterprise',
      costOne: 0,
      costTwo: 2000,
      costThree: 5000,
      costFour: 10000,
    },
    {
      quoteName: 'cms integration',
      startingValue: 25,
      steps: 25,
      selectionOne: 'None',
      selectionTwo: 'Basic',
      selectionThree: 'Advanced',
      selectionFour: 'Enterprise',
      costOne: 0,
      costTwo: 2000,
      costThree: 4000,
      costFour: 8000
    },
    {
      quoteName: 'platform',
      startingValue: 12.5,
      steps: 12.5,
      selectionOne: 'Custom',
      selectionTwo: 'Shopify',
      selectionThree: 'Webflow',
      selectionFour: 'Wix',
      selectionFive: 'Rocketspark',
      selectionSix: 'Squarespace',
      selectionSeven: 'Wordpress',
      selectionEight: 'Woocommerce',
      discountOne: 0,
      discountTwo: 10,
      discountThree: 25,
      discountFour: 30,  
      discountFive: 30,
      discountSix: 25,
      discountSeven: 25,
      discountEight: 25
    },
]